# 搜索建议配置

[netease]
suggestions = ["音乐排行榜", "热门歌曲", "最新专辑", "歌手合集", "经典老歌"]

[youtube]
suggestions = ["热门视频", "最新上传", "视频教程", "电影剪辑", "游戏直播"]

[bilibili]
suggestions = ["番剧更新", "游戏解说", "科技资讯", "生活vlog", "美食制作"]

[default]
suggestions = ["热门推荐", "最新内容", "精选合集", "热门话题", "相关内容"]
